package com.example.dicedistributionsimulator.shared;

public enum ValidationMessage {

    NUMBER_OF_SIDES_IS_REQUIRED,
    NUMBER_OF_SIDES_SHOULD_BE_GREATER_OR_EQUAL_TO_FOUR,
    NUMBER_OF_SIDES_SHOULD_NOT_BE_AN_ODD_NUMBER,
    INVALID_ROLL_RESULT_INPUT_VALUE,
    ROLL_RESULT_VALUE_SHOULD_BE_GREATER_THAN_ZERO,
    INVALID_INPUT_VALUE_FOR_ID,
    TOTAL_NUMBER_OF_ROLLS_IS_REQUIRED,
    TOTAL_NUMER_OF_ROLLS_SHOULD_BE_GREATER_OR_EQUAL_TO_ONE,
    DICE_IS_REQUIRED,
    NUMBER_OF_DICES_IS_REQUIRED,
    NUMER_OF_DICES_SHOULD_BE_EQUAL_OR_GREATER_THAN_ONE,
    SIMULATION_RESULTS_ARE_EMPTY;

    @Override
    public String toString() {
        return this.name().toLowerCase().replace("_", ".");
    }
}
